apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-app-of-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/bookinfo-servicemesh-demo.git
    targetRevision: webinar
    path: argocd-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      allowEmpty: true
