apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: servicemeshcontrolplanes-maistra-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: bookinfo-servicemesh
roleRef:
  kind: ClusterRole
  name: servicemeshcontrolplanes.maistra.io-v2-admin
  apiGroup: rbac.authorization.k8s.io
