apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/bookinfo-servicemesh-demo.git
    targetRevision: HEAD
    path: argocd-config
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
