apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
spec:
  project: default
  source:
    repoURL: https://github.com/earvonen/cool-lab-gitops.git
    targetRevision: HEAD
    path: argocd-config
  destination:
    server: https://kubernetes.default.svc
    namespace: multicloud-gitops-region-one
