apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/bookinfo-servicemesh-demo.git
    targetRevision: HEAD
    path: applications/bookinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo
  syncPolicy:
    automated:
      selfHeal: true
