apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-servicemesh
spec:
  project: default
  source:
    repoURL: https://github.com/earvonen/cool-lab-gitops.git
    targetRevision: HEAD
    path: applications/bookinfo-servicemesh
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-servicemesh
