apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-app-of-apps
  namespace: openshift-operators
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/bookinfo-servicemesh-demo.git
    targetRevision: HEAD
    path: argocd-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
