apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: bookinfo-servicemesh
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/bookinfo-servicemesh-demo.git
    targetRevision: HEAD
    path: applications/bookinfo-servicemesh
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-servicemesh
  syncPolicy:
    automated:
      allowEmpty: true
