apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  finalizers:
  - maistra.io/istio-operator
  generation: 1
  name: basic
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  policy:
    type: Istiod
  profiles:
  - default
  security:
    dataPlane:
      mtls: true
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.3
